inputs:
  product:
    description: 'a product, available options: intellij_idea, pycharm'
    required: true
  version:
    description: 'build number'
    required: true
runs:
  using: composite
  steps:
    - uses: ./.github/actions/free_disk_space_and_expand_swap
    - name: Build environment
      shell: bash
      env:
        product: ${{inputs.product}}
      # language=bash
      run: docker build . --target $product --tag $product
    - name: Build
      shell: bash
      env:
        product: ${{inputs.product}}
        version: ${{inputs.version}}
      # language=bash
      run: docker run --rm --user "$(id -u)" --volume "${PWD}:/community" $product -Dbuild.version=$version