on:
  # we have to run on push for all release branches and pull_request for everything else to avoid github's "feature" where it
  # runs the CI on the merged state but also if there are conflicts it just silently doesn't run anything and doesn't tell you why...
  push:
    branches:
      - release/*

  # we only run on pull_request when the source branch name doesn't start with "release/". unfortunately branches-ignore refers to
  # the source branch not the target branch so we can't do that here. we use an `if` statement in the get_version job instead
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || !startsWith(github.event.pull_request.head.ref, 'release/')
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: ./.github/actions/free_disk_space_and_expand_swap
      - name: run tests
        # currently we only run git tests. list mostly taken from platform/testFramework/testResources/tests/testGroups.properties
        # TODO: figure out what other tests we should run
        run: |
          ./tests.cmd --module intellij.idea.community.main.tests --test "git4idea.*;-git4idea.remote.GitRemoteTest;-com.intellij.openapi.vcs.roots.VcsRootDetectorTest;com.intellij.openapi.vcs.*;com.intellij.testFramework.vcs.*;com.intellij.tasks.vcs.*;com.intellij.vcs.*"
