name: Publish to package managers
on:
  release:
    types: [released]
jobs:
  winget:
    runs-on: ubuntu-slim
    steps:
      - uses: vedantmgoyal9/winget-releaser@4ffc7888bffd451b357355dc214d43bb9f23917e
        with:
          identifier: detachhead.rebased
          token: ${{ secrets.WINGET_TOKEN }}
          installers-regex: ^rebased.exe$

  homebrew:
    runs-on: macos-latest
    steps:
    - uses: FriesI23/action-homebrew-bump-cask@561bbe447f8915a50a62e65483061bea1e7f136f
      with:
        # Required, custom GitHub access token with the 'public_repo' and 'workflow' scopes
        token: ${{ secrets.HOMEBREW_TOKEN }}
        tap: DetachHead/homebrew-tap
        livecheck: false